name: InfinicardVisionModel
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.9
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - torch
      - argparse
      - numpy
      - pyyaml
      - torchvision
      - geojson==3.1.0
      - google-api-core==2.20.0
      - google-auth==2.35.0
      - googleapis-common-protos==1.65.0
      - idna==3.10
      - imagesize==1.4.1
      - labelbox==5.1.0
      - mypy==1.10.1
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pillow==10.4.0
      - proto-plus==1.24.0
      - protobuf==5.28.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygeotile==1.0.6
      - pyproj==3.7.0
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - rsa==4.9
      - shapely==2.0.6
      - six==1.16.0
      - strenum==0.4.15
      - tqdm==4.66.5
      - typeguard==4.3.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - python-dotenv==1.0.1
